apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: todo-namespace
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/prometheus
    type: DirectoryOrCreate
